---
- hosts: all
  tasks:
    - name: Import Remi GPG key.
      rpm_key: "key={{ item }} state=present"
      with_items:
        - "http://rpms.famillecollet.com/RPM-GPG-KEY-remi"
      become: true

    - name: Install Remi repo.
      command: "rpm -Uvh --force {{ item.href }} creates={{ item.creates }}"
      with_items:
        - href: "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
          creates: "/etc/yum.repos.d/remi.repo"
      become: true

    - name: Install NPM, NodeJS and Forever.
      include_role: name=nodejs

    - name: Ensure NodeJS app folder exists.
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example NodeJS app to server.
      copy: "src=app dest={{ node_apps_location }}"

    - name: Install example app dependencies.
      npm: "path={{ node_apps_location }}/app"

    - name: Check the list of the running Forever applications.
      command: forever list
      register: forever_list

    # - debug: "msg={{ forever_list }}"

    - name: Start example NodeJS application.
      command: "forever start {{ node_apps_location }}/app/index.js"
      when: "forever_list.stdout.find('{{ node_apps_location }}/app/index.js') == -1"
