# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  # App server 1
  config.vm.define "app" do |app|
    app.vm.hostname = "orc-app.test"
    app.vm.network :private_network, ip: "192.168.60.2"
  end
end
