---
- hosts: all
  become: true

  vars_files:
    - vars.yaml

  handlers:
    - name: restart_apache
      service: name=apache2 state=restarted

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=3600

  tasks:
    - name: Get software for apt repository management.
      apt: "name={{ item }} state=present"
      with_items:
        - python-apt
        - python-pycurl

    - name: Install ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' state=present

    - name: Install Apache, MySQL, PHP, and other dependencies.
      apt: "name={{ item }} state=present"
      with_items:
        - git
        - curl
        - sendmail
        - apache2
        - php5.6
        - php5.6-common
        - php5.6-mysql
        - php5.6-cli
        - php5.6-curl
        - php5.6-gd
        - php5.6-dev
        - php5.6-mcrypt
        - php5.6-apcu
        - php-pear
        - php5.6-mysql
        - mysql-server

    - name: Start Apache, MySQL, and PHP.
      service: "name={{ item }} state=started enabled=true"
      with_items:
        - apache2
        - mysql

    - name: Enable Apache rewrite module (required by Drupal).
      apache2_module: name=rewrite state=present
      notify: restart_apache

    - name: Add Apache virtual virtualhost for Drupal 8 development.
      template:
        src: "templates/drupal.dev.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: restart_apache

    - name: Symlink Drupal virtualhost to sites-enabled.
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
        state: link
      notify: restart_apache

    - name: Remove default virtualhost file.
      file:
        path: /etc/apache2/sites-enabled/000-default
        state: absent
      notify: restart_apache

    - name: Enable upload progress via APC.
      lineinfile:
        dest: /etc/php/5.6/apache2/conf.d/20-apcu.ini
        regexp: "^apc.rfc1867"
        line: "apc.rfc1867 = 1"
        state: present
      notify: restart_apache

    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run Composer installer.
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move Composer into globally-accessible location.
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: Check out drush master branch.
      git:
        repo: https://github.com/drush-ops/drush.git
        dest: /opt/drush

    - name: Install Drush dependencies with Composer.
      shell: >
        /usr/local/bin/composer install
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: Create drush bin symlink.
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link
