---
- hosts: all
  become: true

  vars_files:
    - vars.yaml

  handlers:
    - name: restart_apache
      service: name=apache2 state=restarted

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=3600

  tasks:
    - name: Get software for apt repository management.
      apt: "name={{ item }} state=present"
      with_items:
        - python-apt
        - python-pycurl
        - python3-pip

    - name: Install ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' state=present

    - name: Install Apache, MySQL, PHP, and other dependencies.
      apt: "name={{ item }} state=present"
      with_items:
        - git
        - curl
        - sendmail
        - apache2
        - php7.4
        - php7.4-common
        - php7.4-mysql
        - php7.4-cli
        - php7.4-curl
        - php7.4-xml
        - php7.4-gd
        - php7.4-dev
        - php7.4-mcrypt
        - php7.4-apcu
        - php-pear
        - php7.4-mysql
        - mysql-server

    - name: Start Apache, MySQL, and PHP.
      service: "name={{ item }} state=started enabled=true"
      with_items:
        - apache2
        - mysql

    - name: Enable Apache rewrite module (required by Drupal).
      apache2_module: name=rewrite state=present
      notify: restart_apache

    - name: Add Apache virtual virtualhost for Drupal 8 development.
      template:
        src: "templates/drupal.dev.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: restart_apache

    - name: Symlink Drupal virtualhost to sites-enabled.
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
        state: link
      notify: restart_apache

    - name: Remove default virtualhost file.
      file:
        path: /etc/apache2/sites-enabled/000-default
        state: absent
      notify: restart_apache

    - name: Enable upload progress via APC.
      lineinfile:
        dest: /etc/php/5.6/apache2/conf.d/20-apcu.ini
        regexp: "^apc.rfc1867"
        line: "apc.rfc1867 = 1"
        state: present
      notify: restart_apache

    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present

    - name: Remove MySQL test database.
      mysql_db:
        name: test
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create a database fro Drupal.
      mysql_db:
        name: "{{ domain }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Download Composer installer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run Composer installer.
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move Composer into globally-accessible location.
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: Check out drush master branch.
      git:
        repo: https://github.com/drush-ops/drush.git
        dest: /opt/drush
        version: 7.x

    - name: Install Drush dependencies with Composer.
      shell: >
        /usr/local/bin/composer install --no-interaction
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: Create Drush bin symlink.
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link

    - name: Checkout the Drupal Core to the Apache docroot.
      git:
        repo: http://git.drupal.org/project/drupal.git
        version: "{{ drupal_core_version }}"
        dest: "{{ drupal_core_path }}"

    - name: Install Drupal.
      command: >
        drush si -y --site-name="D7 Test" --account-name=admin
        --account-pass=admin --db-url="mysql://root@localhost/drupaltest"
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/default/settings.php
      notify: restart_apache

    - name: Set permissions properly on Drupal settings.php
      file:
        path: "{{ drupal_core_path }}/sites/default/settings.php"
        mode: 0744

    - name: Set permissions on Drupal files directory.
      file:
        path: "{{ drupal_core_path }}/sites/default/files"
        mode: 0777
        state: directory
        recurse: true
