---
- hosts: all
  vars_files:
    - vars.yaml

  handlers:
    - name: restart_apache
      service: name=apache2 stater=restarted
      become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=3600
      become: true

  tasks:
    - name: Get software for apt repository management.
      apt: "name={{ item }} state=present"
      become: true
      with_items:
        - python-apt
        - python-pycurl

    - name: Install ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' state=present
      become: true

    - name: Install Apache, MySQL, PHP, and other dependencies.
      apt: "name={{ item }} state=present"
      become: true
      with_items:
        - git
        - curl
        - sendmail
        - apache2
        - php5.6
        - php5.6-common
        - php5.6-mysql
        - php5.6-cli
        - php5.6-curl
        - php5.6-gd
        - php5.6-dev
        - php5.6-mcrypt
        - php5.6-apcu
        - php-pear
        - php5.6-mysql
        - mysql-server

    - name: Start Apache, MySQL, and PHP.
      service: "name={{ item }} state=started enabled=true"
      become: true
      with_items:
        - apache2
        - mysql

    - name: Enable Apache rewrite module (required by Drupal).
      apache2_module: name=rewrite state=present
      notify: restart_apache

    - name: Add Apache virtual virtualhost for Drupal 8 development.
      template:
        src: "templates/drupal.dev.conf.js"
        dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: restart_apache

    - name: Symlink Drupal virtualhost to sites-enabled.
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
        state: link
      notify: restart_apache

    - name: Remove default virtualhost file.
      file:
        path: /etc/apache2/sites-enabled/000-default
        state: absent
      notify: restart_apache
