# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 1000
    v.linked_clone = true
  end

  # Solr server
  config.vm.define "solr" do |app|
    app.vm.hostname = "orc-solr.test"
    app.vm.network :private_network, ip: "192.168.60.2"
  end
end
