---
- hosts: centos
  become: true

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted

  tasks:
    - name: Ensure Apache is installed.
      yum:
        name: httpd
        state: present

    - name: Copy configuration file.
      copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart_apache

    - name: Flush handlers.
      meta: flush_handlers

    - name: Add an environment variable to the remote machine's shell.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: "^ENV_VAR="
        line: "ENV_VAR=value"
      become: false

    - name: Register the environment variable.
      shell: 'source ~/.bash_profile && echo "$ENV_VAR"'
      register: foo
      become: false

    - debug: msg="The environment variable value is {{ foo.stdout }}"

    - name: Ensure Apache is running and starts at boot.
      service:
        name: httpd
        state: started
        enabled: true
