---
- hosts: centos
  become: true

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted

  tasks:
    - name: Ensure Apache is installed.
      yum:
        name: httpd
        state: present

    - name: Copy configuration file.
      copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart_apache

    - name: Flush handlers.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot.
      service:
        name: httpd
        state: started
        enabled: true
