---
- name: Install Apache Tomcat9 and Solr.
  hosts: ubuntu

  vars_files:
    - vars.yaml

  handlers:
    - name: restart_tomcat
      service: tomcat=9 state=restarted
      become: true

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=true cache_valid_time=3600
      become: true

    - name: Install Tomcat9.
      apt:
        name:
          - tomcat9
          - tomcat9-admin
        state: present
      become: true

    - name: Ensure Tomcat 9 is started and enabled on boot
      service: name=tomcat9 state=started enabled=true
      become: true

    - name: Make sure Tomcat9 is listening on port 8080.
      uri:
        url: "http://localhost:8080"
        method: GET
        status_code: 200

    - name: Download Solr.
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz?action=download"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Expand Solr.
      unarchive:
        remote_src: true
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.md"

    - name: Copy Solr components into the place.
      shell: >
        cp -r {{ item.src }} {{ item.dest }}
        creates={{ item.creates }}
      with_items:
        # Solr example configuration and war file.
        - src: "{{ solr_dir }}/example/webapps/solr.war"
          dest: "{{ solr_dir }}/solr.war"
          creates: "{{ solr_dir }}/solr.war"
        - src: "{{ solr_dir }}/example/solr/*"
          dest: "{{ solr_dir }}/"
          creates: "{{ solr_dir }}/solr.xml"
        # Solr log4j logging configuration.
        - src: "{{ solr_dir }}/example/lib/ext/*"
          dest: "/var/lib/tomcat9/shared/"
          creates: "/var/lib/tomcat9/shared/log4j-1.2.16.jar"
        - src: "{{ solr_dir }}/example/resources/log4j.properties"
          dest: "/var/lib/tomcat9/shared/classes"
          creates: "/var/lib/tomcat9/shared/classes/log4j.properties"
      notify: restart_tomcat

    - name: Ensure Solr example directory is absent.
      file:
        path: "{{ solr_dir }}/example"
        state: absent

    - name: Set up Solr data directory.
      file:
        path: "{{ solr_dir }}/data"
        state: directory
        owner: tomcat9
        group: tomcat9

    - name: Configure solrconfig.xml for new data directory.
      lineinfile:
        dest: "{{ solr_dir }}/collection1/conf/solrconfig.xml"
        regexp: "^.*<dataDir.+$"
        line: "<dataDir>${solr.data.dir:{{ solr_dir }}/data}</dataDir>"
        state: present

    - name: Set permissions for solr home.
      file:
        path: "{{ solr_dir }}"
        recurse: true
        owner: tomcat9
        group: tomcat9

    - name: Add Catalina configuration for solr.
      template:
        src: templates/solr.xml.j2
        dest: /etc/tomcat7/Catalina/localhost/solr.xml
        owner: root
        group: tomcat7
        mode: 0644
      notify: restart_tomcat
